### ISSUE TITLE
Noti does not reconnect after sleep

### ISSUE THREAD

**Issue by joe776** [jariz/Noti#66] opened 2017-12-23 11:51 UTC
For me it looks like the latest version (0.3) does not automatically reconnect after sleep.
Those are the latest lines in the log:
```13:37:12.438 [38;5;35mDEBUG[0m PushManager.init():41 - Getting user info...
13:37:13.731 [38;5;35mDEBUG[0m Is connected.websocketDidConnect():279 - PushManager
15:13:42.172 [38;5;178mWARNING[0m Is disconnected: Optional("The operation couldn’t be completed.websocketDidDisconnect():283 - PushManager
15:13:42.172 [38;5;38mINFO[0m PushManager.websocketDidDisconnect():286 - Reconnecting in 5 sec
15:13:44.277 [38;5;178mWARNING[0m PushManager.disconnect():52 - Trigged disconnect
15:13:48.150 [38;5;35mDEBUG[0m Is connected.websocketDidConnect():279 - PushManager
15:23:55.553 [38;5;178mWARNING[0m PushManager.disconnect():52 - Trigged disconnect
15:23:55.554 [38;5;178mWARNING[0m Is disconnected: nil.websocketDidDisconnect():283 - PushManager
15:23:55.554 [38;5;197mERROR[0m PushManager.websocketDidDisconnect():296 - Not going to reconnect: I'm killed
12:41:46.287 [38;5;38mINFO[0m AppDelegate.applicationWillTerminate():78 - Going to terminate Noti.
12:41:49.712 [38;5;35mDEBUG[0m PushManager.initCrypt():67 - Encryption enabled!
12:41:49.714 [38;5;35mDEBUG[0m PushManager.init():41 - Getting user info...
12:41:51.918 [38;5;35mDEBUG[0m Is connected.websocketDidConnect():279 - PushManager
```
BTW, could the date be included in the log messages? The disconnect and the reconnect (through a restart) did not happen on the same day, which is not obvious from the messages.

I'm running macOS High Sierra 10.13.2 (17C88) on a MBP Mid 2014.

**Comment by yamaha252** [comment] 2017-12-25 09:08
I have the same issue.
10.13.2 (17C88)

**Comment by OrkunDzgn** [comment] 2017-12-26 10:32
It was happening before 0.3. I used to have this error but haven't tried on 0.3 yet but as far as I can see, it still exists since you guys are telling.

OS Version: 10.13.2
Noti Version: 0.3 (Not tested yet)

**Comment by bjptwist** [comment] 2017-12-28 13:02
I'm too facing this issue since updating to 0.3.

**Comment by bertildaniel** [comment] 2018-01-11 10:54
Same problem with 0.3, also on 10.13.2. Consistenly logged out after sleep, never a problem with 0.2 will downgrade now until this is fixed.

**Comment by Floowk** [comment] 2018-01-13 19:54
I have the same problem too since the last update.

**Comment by kovinepanda** [comment] 2018-01-17 15:59
I have the same problem too.
@sagarwadhwa1 you don't need to reauthenticate, just quit from Noti and open it again ;)

**Comment by ABeltramo** [comment] 2018-01-19 11:15
Can you try with the new Release (https://github.com/jariz/Noti/releases/tag/0.3.1 v3.1) if the issue is gone? It's working perfectly now on my end.

**Comment by Floowk** [comment] 2018-01-21 13:18
Yes, it seems to be OK :)
Thanks a lot for the update !

**Comment by bertildaniel** [comment] 2018-01-21 17:52
@ABeltramo I've been using latest release for last 2 days without any issue. Thanks!

**Comment by jariz** [comment] 2018-01-22 09:35
OK, We've now had numerous reports that this does not seem to be an issue anymore in 0.3.1.
Feel free to comment here (with logs attached) if you are still experiencing similar problefms, but we're closing this for now.

**Closed by jariz** 2018-01-22 09:35 UTC
Labels: 0.3.1, bug
