### ISSUE TITLE
Need to re-authenticate frequently

### ISSUE THREAD

**Issue by tokestermw** [jariz/Noti#35] opened 2016-12-13 19:46 UTC
Hi, thanks for the app.

I'm on my Mac and use Noti to mirror notifications from my Android phone.

It seems to get disconnected frequently and I have to re-authenticate. I can't seem to pinpoint the cause but I think it happens when WiFi changes or there's no data on my phone. 

The same thing happens on AirDroid but it would be great if there's some visual indicator to see if I'm disconnected.

**Comment by fajor** [comment] 2016-12-14 00:45
Current solution is to close and reopen the app.
An option to reload the app without having to close and reopen would be appreciated.
Or if Noti would automatically reload itself after the Mac comes back from Power Off or Sleep.

**Comment by jariz** [comment] 2016-12-14 10:35
Are you sure you are on the latest version? There's been a disconnected indicator for a while (the icon gets dark), and there was a bug before where it would not reconnect, but that's also long been fixed ([both in 0.1.4](https://github.com/jariz/Noti/issues?q=is%3Aissue+is%3Aclosed+label%3A0.1.4))  

Do you mean reauthenticate as in having to click 'Reauthorize' in the status menu or reauthenticate as in reconnecting to PushBullet?  
You should rarely have to click reauthorize.

**Comment by fajor** [comment] 2016-12-14 18:16
Hi! 

I'm on 0.1.5.

I don't have to click 'Reauthorize' in order to reconnect (it works, but closing and reopening is much simpler).

When this problem arises, I do not get the disconnected indicator.

I'm not 100% sure if putting the Mac to sleep and opening it back up after a couple hours is the source of the problem, but it usually happens then.

Here's what I currently see on Noti:
<img width="593" alt="screen shot 2016-12-14 at 1 09 02 pm" src="https://cloud.githubusercontent.com/assets/18128036/21194724/f2fe3a62-c1fe-11e6-97a9-b15faf7cd27e.png">

On my Nexus 5's Pushbullet app, I can troubleshoot the current problem by sending a test notification:
![screenshot_20161214-130602](https://cloud.githubusercontent.com/assets/18128036/21194762/1d60fdb2-c1ff-11e6-96b6-3335f4f51c51.png)

However it simply does not appear until I close and reopen Noti. After doing so, Noti behaves normally:
<img width="460" alt="screen shot 2016-12-14 at 1 14 57 pm" src="https://cloud.githubusercontent.com/assets/18128036/21194816/5781a94c-c1ff-11e6-9705-998998526984.png">

Other than this though, I'm very happy with your app. Thanks for the help!

**Comment by tokestermw** [comment] 2016-12-14 18:48
I am on 0.1.5 as well and I don't see any notification.

I'm on macOS Sierra 10.12.1 if that matters.

**Comment by jariz** [comment] 2016-12-18 18:37
I really am going to need exact steps to reproduce this or else I won't be able to fix it.
Haven't had this before personally and I keep my mac running for months, putting it to sleep multiple times a day.

**Comment by tokestermw** [comment] 2016-12-20 18:33
Interestingly, I've updated to MacOS 10.12.2 and I haven't had a problem since.

**Comment by benblb** [comment] 2017-01-20 06:15
I'm on MacOS 10.12.2 and Noti constantly stops working. Tried putting my Mac to sleep to see if that breaks it, but it did not. It seems to just stop at random. When it does work, however, it's fantastic! 

Off topic: would really love if you could add in the 'dismiss on phone' option since it's quite useful. 

Thanks for creating such a useful tool!

**Comment by jariz** [comment] 2017-01-20 09:56
Would really love to help fix this problem but I've never encountered this before and use it daily ☹️   
@benblb When it stops working, is noti's icon darkened?

**Comment by benblb** [comment] 2017-01-20 17:01
Next time it stops working I'll take a screenshot for you :)

**Comment by Spy-Seth** [comment] 2017-01-26 11:12
Same issue for me. I need to reauthenticate to keep it working.

**Comment by taolmsted** [comment] 2017-04-07 00:13
I, too, am having this issue.  While I don't to reauthenticate, I'm discovering I need to quit the app and then restart it.  The menu bar icon is most certainly not darkened.  I'll begin monitoring more closely to identify perceivable trends.

**Comment by JohnnyMcL** [comment] 2017-08-02 09:43
I am also experiencing the issue where no notifications will be mirrored until I quit and restart the app. This only occurs after my MacBook has been closed for a length of time, usually when I go to sleep for the night, and the app works perfectly well at all other times. I have not encountered the need to reauthenticate, and the menu bar icon does not darken when this occurs.

**Comment by jariz** [comment] 2017-12-20 15:16
Hi all!
We just recently pushed a new update that adds logging functionality in order for us to diagnose issues like this better.
If this issue happens again for you, please send us your logfile!

You can do this by following these steps:

- Make sure you're up to date (click the icon > Check for updates)
- Locate your Noti log file in the `Console.app` (cmd+space, and type `console`)
It'll be here:
![](https://jari.lol/aEvbFJdc7v.png)
- Paste it into a [gist](https://gist.github.com/) and comment the link in this issue.

**Comment by jevy** [comment] 2018-01-05 16:54
Hi @jariz - Just installed this for the first time two days ago. I have to reauthenticate frequently. Here's the log: https://gist.github.com/jevy/0eda795b22763e609ff3e711d8b7f8e5

**Comment by benblb** [comment] 2018-01-06 00:11
I am experiencing this issue, @jariz - thanks for being on top of it!

https://gist.github.com/anonymous/ae0bec7391a0f378c9940669d54efee3

**Comment by MatrixDev** [comment] 2018-01-11 09:45
I'm experiencing same problem. For me it happens constantly after closing mac for few hours. I'm on High Sierra.

This is how Noti looks like:
https://imgur.com/a/F0oHH

Here are logs:

```
20:15:16.542 [38;5;38mINFO[0m PushManager.websocketDidDisconnect():286 - Reconnecting in 5 sec
20:15:17.986 [38;5;178mWARNING[0m PushManager.disconnect():52 - Trigged disconnect
20:15:21.548 [38;5;178mWARNING[0m Is disconnected: Optional("The operation couldn’t be completed.websocketDidDisconnect():283 - PushManager
20:15:21.549 [38;5;38mINFO[0m PushManager.websocketDidDisconnect():286 - Reconnecting in 5 sec
21:08:28.174 [38;5;178mWARNING[0m Is disconnected: Optional("The operation couldn’t be completed.websocketDidDisconnect():283 - PushManager
21:08:28.174 [38;5;38mINFO[0m PushManager.websocketDidDisconnect():286 - Reconnecting in 5 sec
21:08:33.179 [38;5;178mWARNING[0m Is disconnected: Optional("The operation couldn’t be completed.websocketDidDisconnect():283 - PushManager
21:08:33.179 [38;5;38mINFO[0m PushManager.websocketDidDisconnect():286 - Reconnecting in 5 sec
21:08:38.185 [38;5;178mWARNING[0m Is disconnected: Optional("The operation couldn’t be completed.websocketDidDisconnect():283 - PushManager
21:08:38.186 [38;5;38mINFO[0m PushManager.websocketDidDisconnect():286 - Reconnecting in 5 sec
21:08:46.842 [38;5;35mDEBUG[0m Is connected.websocketDidConnect():279 - PushManager
00:02:26.696 [38;5;178mWARNING[0m PushManager.disconnect():52 - Trigged disconnect
00:02:26.749 [38;5;178mWARNING[0m Is disconnected: nil.websocketDidDisconnect():283 - PushManager
00:02:26.750 [38;5;197mERROR[0m PushManager.websocketDidDisconnect():296 - Not going to reconnect: I'm killed
```

**Comment by ABeltramo** [comment] 2018-01-19 11:19
Can you try with the new Release (https://github.com/jariz/Noti/releases/tag/0.3.1 v3.1) if the issue is gone? It's working perfectly now on my end.

**Comment by tokestermw** [comment] 2018-01-21 23:37
I've been using 0.3.1 for the past few days. Looks good!

Looks like it's working for various situations: after sleep, using a VPN, tethering, no WiFi, etc.

**Comment by jariz** [comment] 2018-01-22 09:35
OK, We've now had numerous reports that this does not seem to be an issue anymore in 0.3.1.
Feel free to comment here (with logs attached) if you are still experiencing similar problefms, but we're closing this for now.

**Closed by jariz** 2018-01-22 09:35 UTC
Labels: 0.3.1, investigating
